CREATE OR REPLACE TRIGGER ProductDeals_QuantityOnHand
AFTER INSERT ON PRODUCTDEALS_TRANSPART
   FOR EACH ROW
    BEGIN
    
        UPDATE  PRODUCTDEALS_PART PDP
        SET     UNITS_ON_HAND = UNITS_ON_HAND - :NEW.NUMBER_ORDERED
        FROM    PRODUCTDEALS_TRANSPART PDTP
        WHERE   PDP.PART_NUMBER = NEW.PDTP.PART_NUMBER
    
    END;