CREATE VIEW ProductDeals_CustomerWorth AS
SELECT CUSTOMER_NUMBER, COUNT(*) AS NUM_TRANS, SUM(QUOTED_PRICE)
FROM PRODUCTDEALS_CUSTOMER PDC, PRODUCTDEALS_TRANS PDT, PRODUCTDEALS_TRANSPART PDTP
WHERE PDC.CUSTOMER_NUMBER = PDT.CUSTOMER_NUMBER PDTP.TRANS_NUMBER = PDT.TRANS_NUMBER;