
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 6;
  public static final int NUM = 5;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int ID = 3;
  public static final int error = 1;
  public static final int PRINT = 8;
  public static final int SEMICOLON = 4;
  public static final int EQUALS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "ID",
  "SEMICOLON",
  "NUM",
  "MINUS",
  "EQUALS",
  "PRINT"
  };
}

