//----------------------------------------------------
// The following code is a manually-created simulation
// of the symbol code generated by CUP
//
// NOTE TO STUDENTS: You will need to add any new
// symbols you require for the Lexer into this file!
//----------------------------------------------------

public class sym {
  /* terminals */
  public static final int EOF = 1;
  public static final int PLUS = 2;
  public static final int NUM = 3;
}

