//----------------------------------------------------
// The following code is a manually-created simulation
// of the symbol code generated by CUP
//
// NOTE TO STUDENTS: You will need to add any new
// symbols you require for the Lexer into this file!
//----------------------------------------------------

public class sym {
  /* terminals */
  public static final int EOF = 1;
  public static final int PLUS = 2;
  public static final int NUM = 3;
  public static final int QSTRING = 4;
  public static final int NUMTYPE = 5;
  public static final int ID = 6;
  public static final int ASSIGN = 7;
  public static final int SC = 8;
  public static final int PRINT = 9;
  public static final int STRING = 10;
  public static final int TEXT = 11;
  public static final int BOOL = 12;
  public static final int AND = 13;
  public static final int OR = 14;
  public static final int NOT = 15;
  public static final int TRUE = 16;
  public static final int FALSE = 17;
  public static final int LIST = 18;
  public static final int LT = 19;
  public static final int GT = 20;
  public static final int OPCURLY = 21;
  public static final int CLCURLY = 22;
  public static final int COMMA = 23;
  public static final int READ = 24;
  public static final int ERROR = 25;
  public static final int EXIT = 26;
  public static final int FUNC = 27;
  public static final int VOID = 28;
  public static final int INPUT = 29;
  public static final int UNTIL = 30;
  public static final int OPSQUARE = 31;
  public static final int CLSQUARE = 32;
  public static final int OPPAREN = 33;
  public static final int CLPAREN = 34;
  public static final int DIVIDE = 35;
  public static final int OPFILTER = 36;
  public static final int CLFILTER = 37;
  public static final int WRITE = 38;
  public static final int IF = 39;
  public static final int ELSE = 40;
  public static final int FOR = 41;
  public static final int COLON = 42;
  public static final int RETURN = 43;
  public static final int SWITCH = 44;
  public static final int CASE = 45;
  public static final int DEFAULT = 46;
  public static final int MINUS = 47;
  public static final int TIMES = 48;
  public static final int MODULUS = 49;
  public static final int LTE = 50;
  public static final int GTE = 51;
  public static final int EQUALS = 52;
  public static final int APPEND = 53;
}

