//----------------------------------------------------
// The following code is a manually-created simulation
// of the symbol code generated by CUP
//
// NOTE TO STUDENTS: You will need to add any new
// symbols you require for the Lexer into this file!
//----------------------------------------------------

public class sym {
  /* terminals */
  public static final int EOF = 1;
  public static final int PLUS = 2;
  public static final int MINUS = 3;
  public static final int EQUALS = 4;
  public static final int PRINT = 5;
  public static final int NUM = 6;
  public static final int ID = 7;
}

